namespace :archive do

    desc 'Build plugin'
    task build: %w(package)
    #MYPATH = ENV['MYPATH'] = "/home/dror/rake_test/session_pa/my_archive/build"
    #EXCLUDE_BAK = ENV['EXCLUDE_BAK'] = "*.bak"
    MYPATH = ENV["MYPATH"] || "my_archive/build"
    EXCLUDE_TXT = ENV['EXCLUDE_TXT'] || "*.txt"
    EXCLUDE_BAK = ENV['EXCLUDE_BAK'] || "*.bak"

    desc 'Destroy archive folder and its contents'
    task :destroy do
        rm_rf 'my_archive/build'
    end

    desc 'create a .tar.gz package'
    Rake::PackageTask.new('my_archive', :noversion) do |p|
        p.need_tar_gz = true
        p.package_files.include('*', '*/*')
        p.package_dir = MYPATH
        p.package_files.exclude("#{EXCLUDE_TXT}")
        p.package_files.exclude("#{EXCLUDE_BAK}")
     
    end

end

# how to run : rake archive:build MYPATH=my_archive/build EXCLUDE_TXT="*.txt" EXCLUDE_BAK="*.bak" 
# or
# rake archive:build
